// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiTtmnHF8jp_EHQgi4oI9sICNHdZGFEKc',
    appId: '1:548167490654:web:9dbbe78710bdba6dcba8cf',
    messagingSenderId: '548167490654',
    projectId: 'mews-firebase-example',
    authDomain: 'mews-firebase-example.firebaseapp.com',
    storageBucket: 'mews-firebase-example.appspot.com',
    measurementId: 'G-JPXCDL0EXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRZTHQO3xK-moDMiQaTdouGbOM6kyYALE',
    appId: '1:548167490654:android:180f972937a76840cba8cf',
    messagingSenderId: '548167490654',
    projectId: 'mews-firebase-example',
    storageBucket: 'mews-firebase-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyxZld9eNd9wnj1ZowERpjzpK_4L9kUoM',
    appId: '1:548167490654:ios:ce8ce07f65ff8de9cba8cf',
    messagingSenderId: '548167490654',
    projectId: 'mews-firebase-example',
    storageBucket: 'mews-firebase-example.appspot.com',
    iosClientId: '548167490654-feg3vd8i9ha55jgeq09pvuckrhhsriic.apps.googleusercontent.com',
    iosBundleId: 'com.example.mewsTalkFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyxZld9eNd9wnj1ZowERpjzpK_4L9kUoM',
    appId: '1:548167490654:ios:ce8ce07f65ff8de9cba8cf',
    messagingSenderId: '548167490654',
    projectId: 'mews-firebase-example',
    storageBucket: 'mews-firebase-example.appspot.com',
    iosClientId: '548167490654-feg3vd8i9ha55jgeq09pvuckrhhsriic.apps.googleusercontent.com',
    iosBundleId: 'com.example.mewsTalkFirebase',
  );
}
